apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
spec:
  serviceName: "solr"
  replicas: 2
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-solr-data
        image: busybox
        command: ['sh', '-c', 'mkdir -p /store/data && chown 8983:8983 /store/data']
        volumeMounts:
        - name: solr-data
          mountPath: /store
      - name: init-solr-logs
        image: busybox
        command: ['sh', '-c', 'mkdir -p /store/logs && chown 8983:8983 /store/logs']
        volumeMounts:
        - name: solr-data
          mountPath: /store
      - name: init-solr-xml
        image: solr:latest
        command: ['sh', '-c', '[ ! -f /store/data/solr.xml ] && cp /opt/solr/server/solr/solr.xml /store/data/solr.xml || true']
        volumeMounts:
        - name: solr-data
          mountPath: /store
      containers:
      - name: solr
        image: solr:latest
        ports:
        - containerPort: 2181
          name: solr-port
        volumeMounts:
        - name: solr-data
          mountPath: /store
        env:
        - name: SOLR_HOME
          valueFrom:
            configMapKeyRef:
              name: solr-config
              key: solrHome
        - name: SOLR_PORT
          valueFrom:
            configMapKeyRef:
              name: solr-config
              key: solrPort
        - name: ZK_HOST
          valueFrom:
            configMapKeyRef:
              name: solr-config
              key: zkHost
        - name: SOLR_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SOLR_LOGS_DIR
          valueFrom:
            configMapKeyRef:
              name: solr-config
              key: solrLogsDir
  volumeClaimTemplates:
  - metadata:
      name: solr-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 25Gi